package = "moonscript-parser"
version = "dev-1"

source = {
  url = "git+https://github.com/leafo/moonscript-parser.git"
}

description = {
  summary = "Compiled (C) parser for the MoonScript language",
  detailed = [[
    The new fast MoonScript parser, as native module generated by pgen.
  ]],
  homepage = "https://github.com/leafo/moonscript-parser",
  license = "MIT"
}

dependencies = {
  "lua >= 5.1"
}

build = {
  type = "builtin",
  modules = {
    ["moonscript_parser"] = "moonscript_parser/init.lua",
    ["moonscript_parser.tree"] = "moonscript_parser/tree.lua",
    ["moonscript_parser.errors"] = "moonscript_parser/errors.lua",
    ["moonscript_parser.native"] = {
      sources = { "moonscript_parser.c" }
    }
  }
}
